### ISSUE TITLE
English language does not apply

### ISSUE THREAD

**Issue by rovsita** [opentoonz/xdts_viewer#1]
I have selected the "ok" button and restarted the program, but the interface is still in Japanese

![imagen_2024-10-22_014802301](https://github.com/user-attachments/assets/cfc3bd3f-45d5-4cdf-b952-42dce6ae0e31)

**Comment by shun-iwasawa** [comment]
Oh, I found a cause of the bug. I'll fix it right away. So sorry for inconvenience.

**Comment by shun-iwasawa** [comment]
Replaced the Windows ZIP by the fixed version. MacOS pkg will be replaced soon.

**Comment by shun-iwasawa** [comment]
MacOS pkg has been replaced as well.
